import { Fredoka } from "next/font/google";
import "@/styles/all.scss";
import styles from "./page.module.scss";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // tùy bạn cần
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable}`}>
        {children}
      </body>
    </html>
  );
}
